Telefon doğrulamasıyla parola sıfırlama işlemi yap
omu/nokul pull request #1939
Opened 2020-07-29 10:07 UTC by ecylmz

#### Bu PR'in yaptığı işi/değişikliği ve bu işi/değişikliği neden yaptığını açıklayın

Bu PR, Devise'ın email ile parola sıfırlama servisi yerine telefon doğrulamasıyla parola sıfırlama işlemi yapar.
Güvenlik amaçlı recaptcha servisi de aktif hale getirildi.

Kullanıcının kimliğini doğrulamak için Rails 6.1 ile gelen [signed_id](https://github.com/rails/rails/pull/39313) özelliğinden de faydalandım.

#### İlgili/kapatılacak iş kayıtları

N/A

#### Teknik borç kayıtları

N/A

#### Veritabanına etkileri

N/A

#### Sistem etkileri

N/A

#### Kontrol listesi

- [x] [Katkı sağlama dokümanını](../blob/master/.github/CONTRIBUTING.md) okudum
- [x] İş kaydının başlığı kurallara (sadece ilk harf büyük, emir kipinde problem cümlesi) uygun
- [x] Yapılan iş/değişikliği dokümante ettim
- [x] Yapılan iş/değişikliğin testlerini yazdım
- [x] Test coverage oranını kontrol ettim
- [x] Kod kalitesi (karma) ve test suite dahil olmak üzere tüm entegre kontroller başarıyla geçiyor
- [x] Kendimi bu PR'e assign ettim
- [x] Yapılan iş/değişiklik ile ilgili proje üyelerinden review talep ettim
- [x] Gerekli etiketlemeyi (ör. bug) yaptım

2020-08-03 21:22 UTC, isubas requested changes
Eline sağlık @ecylmz :tada: :+1:

2020-08-03 21:22 UTC, isubas commented on app/services/password_recovery_service.rb
> +                :new_password,
`new_` ön eki gereksiz kaldırabilirsin.

2020-08-03 21:22 UTC, isubas commented on app/controllers/account/password_recovery_controller.rb
> +      @password_recovery = PasswordRecoveryService.new(params[:password_recovery])
parametre kontrolünü es geçmeyelim. Bknz: https://api.rubyonrails.org/classes/ActionController/StrongParameters.html

```ruby
def password_recovery_params
   params.required(:password_recovery).permit(:id_number, :mobile_phone)
end
```

```ruby
PasswordRecoveryService.new(password_recovery_params)
```

2020-08-03 21:22 UTC, isubas commented on app/controllers/account/password_recovery_controller.rb
> +        redirect_to(password_recovery_new_password_path(token: signed_id),
```suggestion
        redirect_to(password_recovery_new_password_path(token: @password_recovery.signed_id),
```

2020-08-03 21:22 UTC, isubas commented on config/routes/account.rb
> +  get 'password_recovery/new_password',         to: 'password_recovery#edit'
`new_password` yerine `update`, `new` gibi basit bir keyword kullanabilirsin. Bu tamamen opsiyonel

2020-08-03 22:25 UTC, roktas approved these changes
Eline sağlık!

2020-08-03 22:25 UTC, roktas commented on app/services/password_recovery_service.rb
> +    errors.add(:base, I18n.t('.account.password_recovery.not_send_verify_code')) && nil
kısayolları severim ama burada daha açık yazmak en güzeli

```suggestion
    errors.add(:base, I18n.t('.account.password_recovery.not_send_verify_code'))
    false
```

2020-08-03 22:25 UTC, roktas commented on app/services/password_recovery_service.rb
> +    errors.add(:base, I18n.t("twilio.errors.#{response.error_code}")) && nil
```suggestion
    errors.add(:base, I18n.t("twilio.errors.#{response.error_code}"))
    false
```

2020-08-03 22:25 UTC, roktas commented on test/system/reset_password_flow_test.rb
> +      skip # TODO: SMS ile nasıl yapılacak daha sonra değerlendirilmeli
webmock ile birşeyler yapılabilir

2020-08-04 08:07 UTC, huseyin commented on test/system/reset_password_flow_test.rb
> +      skip # TODO: SMS ile nasıl yapılacak daha sonra değerlendirilmeli
hızlıca bulduğum kaynak: https://thoughtbot.com/blog/testing-sms-interactions

2020-08-04 08:08 UTC, huseyin approved these changes
Eline sağlık :+1:

2020-08-04 17:06 UTC, isubas approved these changes

2020-08-04 17:11 UTC, ecylmz commented
Review için teşekkürler.

2020-08-04 17:11 UTC, merged